services:
  nginx:
    image: nginx:stable-alpine
    container_name: shroom_shop_nginx
    restart: unless-stopped
    ports:
      - "8012:80"   # Оставляем, если NPM на другом VPS. Если NPM на этом же VPS — меняем на "8002:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Кладём в conf.d, а не заменяем основной конфиг
      - ./conf/maintenance.html:/usr/share/nginx/html/maintenance.html:ro  # ← добавь
      - static_volume:/app/staticfiles # Путь должен совпадать со STATIC_ROOT в Django
      - media_volume:/app/media  
    networks:
      - web
      - npm_default
    depends_on:
      - web

  web:
    build: .  # Т.к. файл теперь в корне рядом с Dockerfile
    container_name: shroom_shop_web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8011:8000"
    volumes:
      # - .:/app  # Монтируем текущую папку в контейнер
      - static_volume:/app/staticfiles
      - media_volume:/app/media  
    # environment из compose перекрывает значения из .env
    # Для сервера лучше убрать DEBUG=True отсюда и держать его только в .env
    environment:
      - DEBUG=False
    networks:
      - web
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    container_name: shroom_shop_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - web
    depends_on:
      db:
        condition: service_healthy

  db:
    # Внимание: на текущий момент стабильная версия Postgres — 17. 
    # Версии 18 еще нет в официальном Docker Hub (используйте 17 или 16).
    image: postgres:17-alpine 
    container_name: shroom_shop_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # Порт 5432 наружу лучше не открывать для безопасности VPS, 
    # контейнеры внутри сети 'web' и так его видят.
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  web:
    driver: bridge
  npm_default:
    external: true  

volumes:
  postgres_data:
  static_volume:
  media_volume:


