# Generated by Django 5.2 on 2026-06-16 06:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид гриба')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Вид гриба',
                'verbose_name_plural': 'Виды грибов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_assets_name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_assets/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'логотипы, слоганы и прочее',
                'verbose_name_plural': 'логотипы, слоганы и прочее',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['slug'], name='shop_catego_slug_5ac49f_idx'), models.Index(fields=['is_active'], name='shop_catego_is_acti_59c89f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, verbose_name='URL (уникальный, генерируется автоматически)')),
                ('article', models.CharField(max_length=200, unique=True, verbose_name='Артикул')),
                ('note_for_manager', models.TextField(blank=True, default='', verbose_name='Примечание для менеджера')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=200, verbose_name='Страна производства')),
                ('nutrition_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Жиры (г/100г)')),
                ('nutrition_protein', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Белки (г/100г)')),
                ('nutrition_carbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Углеводы (г/100г)')),
                ('nutrition_calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Калорийность (ккал/100г)')),
                ('is_gmo_free', models.BooleanField(default=False, verbose_name='Без ГМО')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Вегетарианский')),
                ('storage_temp_min', models.IntegerField(blank=True, null=True, verbose_name='Мин. температура хранения (°C)')),
                ('storage_temp_max', models.IntegerField(blank=True, null=True, verbose_name='Макс. температура хранения (°C)')),
                ('shelf_life_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок годности (мес.)')),
                ('net_weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес товара без упаковки (г)')),
                ('package', models.CharField(blank=True, default='', max_length=200, verbose_name='Упаковка')),
                ('packaging_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес упаковки (кг)')),
                ('packaging_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Длина упаковки (см)')),
                ('packaging_width', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ширина упаковки (см)')),
                ('packaging_height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Высота упаковки (см)')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('discount_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='Количество на складе')),
                ('out_of_stock_behavior', models.CharField(choices=[('hide', 'Скрыть товар'), ('show', 'Показывать с пометкой')], default='hide', max_length=10, verbose_name='При отсутствии товара')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('popularity', models.IntegerField(db_index=True, default=0, verbose_name='Популярность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория')),
                ('mushroom_types', models.ManyToManyField(blank=True, related_name='products', to='shop.mushroomtype', verbose_name='Виды грибов')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at', 'article'],
                'indexes': [models.Index(fields=['slug'], name='shop_produc_slug_76971b_idx')],
            },
        ),
    ]
