# Generated by Django 5.2 on 2026-06-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, default="", verbose_name="Состав"),
        ),
    ]
