# Generated by Django 5.2 on 2026-06-18 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_contact_info_cart_order_orderitem_productimage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteassets",
            old_name="site_assets_name",
            new_name="name",
        ),
    ]
