# Generated by Django 5.2 on 2026-06-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_rename_site_assets_name_siteassets_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mushroomtype",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="mushroomtype",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="mushroom_types/",
                verbose_name="Изображение",
            ),
        ),
    ]
